"""add category to opportunities

Revision ID: 30eee3ea1dc1
Revises: b1f9849d361a
Create Date: 2026-07-30 20:39:14.628546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30eee3ea1dc1'
down_revision = 'b1f9849d361a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_application', ['student_id', 'opportunity_id'])

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('unique_application', type_='unique')

    # ### end Alembic commands ###
